// Sprite sheet loader + frame map. The sheet is generated by
// scripts/build-sprites.mjs (npm run sprites); an Aseprite export with the
// same layout can replace assets/sesame.png without touching this file.

// Vite asset import: a URL in the dev harness, inlined as a data URL in the
// extension build so content.js is self-contained (no web_accessible_resources).
import sheetUrl from '../../assets/sesame.png'

export const FRAME_W = 32
export const FRAME_H = 32
export const ORIGIN_X = 16 // feet center within a frame
export const ORIGIN_Y = 30

export const IDLE_FRAMES = [0, 1] // sitting, breathing pair (no pupils baked)
export const BLINK_FRAME = 2
export const WALK_FRAMES = [3, 4, 5, 6]
export const SLEEP_FRAMES = [7, 8] // breathing pair
export const STRETCH_FRAMES = [9, 10, 11]
export const YAWN_FRAMES = [12, 13] // mouth ajar, mouth wide
export const ROLL_FRAMES = [14, 15, 16, 17] // side, back, back-wiggle, side
export const EAT_FRAMES = [18, 19] // nibble pair
export const TWITCH_FRAME = 20 // sit with the left ear flicked

export const IDLE_FRAME_MS = 1200 // sit breathing cadence

// Pupil overlay anchors for the sit frames (cat-local px; renderer adds the
// gaze offset). Eyes are at (5,-22) and (10,-22), 3x4 each.
export const SIT_PUPILS: ReadonlyArray<readonly [number, number]> = [
  [6, -21],
  [11, -21],
]

export function loadSpriteSheet(): HTMLImageElement {
  const img = new Image()
  img.src = sheetUrl
  return img
}
